### PR TITLE
API for accessing game environment details and ExistsOn ASTT

### PR DESCRIPTION
**Pull request by lukebemish**
Going to keep this as a draft for now. This PR:
 - Adds an api for accessing game environment details (loader, platform, whether or not it's production)
    - (this might make more sense to shove as an extension somewhere; I'm not sure)
 - Adds `@ExistsOn`, an annotation that delegates to either `@OnlyIn` or `@ClientOnly` and `@DedicatedServerOnly` at compile time depending on the loader, and can be made to only be applied on one loader or the other.
    - Includes a way to get around the issues in #1, assuming they cannot be or are not solved on the forge end - I'll remove that bit assuming they're solved on the other end.

### CODE REVIEW

**Comment by lukebemish** [comment]
Need to test out the test mod; otherwise, I'm waiting for the PR on the forge end to be either closed or merged before this is merged.

**Comment by lukebemish** [comment]
Once I merge it, I'll figure out reformatting for 1.19.3

**Comment by lukebemish** [comment]
Nevermind, just rebased it directly to 1.19.3. Let me know what you think

**Comment by Matyrobbrt** [comment]
Is `ExistsOn` worth it at this point?

**Comment by lukebemish** [comment]
Honestly? Maybe, but I'm not sure. I've yet to hit somewhere where I *needed* to use it but I've come awfully close a few times. I figure we can always leave it stale and poke it if a use case pops up

**Comment by lukebemish** [comment]
Alright, I've thought about this API a bit more; I still believe that an API exposing `@OnlyIn` and the quilt equivalents is a good idea. *However*, half of the time when people use these, they really mean for it to be more of a marking of where it should be used, and don't require the side-stripping capabilities these annotations offer. So, I propose the following: a `@Sided` annotation that, by default, serves as just documentation of which sides it should be used on, with a parameter that can be enabled in order to actually remove the class/method/whatever in the environments in question. You could also split this into two separate annotations if you wanted to - one of which applies the other as well, or the like.

Finally, if/when I get around to writing up the successor to this PR, it will include a side-checker system built into it that ensures that contexts marked as common don't access contexts marked as client-only or server-only explicitly, and so forth. It can't be perfect, but it will be pretty good at catching obvious cases as long as people *use* the annotations (which means adding them to the template mods we've got). I'll look into that in the next few weeks

**Comment by PaintNinja** [comment]
I'm still opposed to side stripping for mods on Forge, but would welcome a TypeCheckingExtension for sidedness with accompanying marker annotations.

There's been discussion regarding this in the past which could be a helpful read for nailing down the specifics:
https://discord.com/channels/313125603924639766/540691915373412393/971014838644011098
https://discord.com/channels/176780432371744769/1014269921619886101/1060358302950760568
https://discord.com/channels/313125603924639766/540691915373412393/932638254224797757

**Comment by lukebemish** [comment]
I've messed around with type checking like this in the form of a Java AP before, and I've read through a bit of what you linked; it should definitely be possible. I think that *encouraging* the use of side stripping stuff is a bad idea, but generally *allowing* it and exposing an API for it is not a bad idea because edge cases will inevitably come up. My thoughts here are to make the use of that feature throw a warning in the compiler and/or need a compiler flag enabled to allow

**Pull request closed without merging**
